name: flutter_starter_riverpod
description: Flutter starter with Riverpod
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.3
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  shared_preferences: ^2.2.2
  easy_localization: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  freezed: ^3.0.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
